### ISSUE TITLE
Autodiscover addons in virtualenv/src subdir

### ISSUE THREAD

**Issue by dreispt** [OxideApps/oxide#5]
The goal is to not worry about addons paths - it should be automatically handled behind the scenes.
For users this is already achieved: when using `pip install` the necessary paths get added to the addons path.

But for developers there is still an issue: we want to create a new module and have it immediately available for Odoo.

My suggestion is have automatically add `virtualenv/src` subdirectories to the addons path.
By convention this should be the place for developers to start their code projects.
This is the place where source code is cloned when using `pip install -e`, so it's consistent.

**Comment by dreispt** [comment]
@sbidoul what do you think?
It could be implemented only for the `odoo start` command.
That makes sense because it already is proactive in filling out parameters for you, such as the database, dbfilter and addons path.

**Comment by sbidoul** [comment]
I generally advise against using virtualenv/src for project code. This is indeed the place where pip installs "-e" dependencies, and it is not really a place where developer should start working, as part of it may be overwritten by a replay of `pip install -r requirements.txt`. This is made even clearer when you manage your virtualenvs with virtualenvwrapper which stores your venv "out of the way" in ~/.virtualenvs/...

One way is to create a setup.py for each project such as [in our template](https://github.com/acsone/acsoo/blob/master/acsoo/templates/project/%2Bproject.name%2B/). That takes care of all dependencies when running `pip install -r requirements.txt -e .` after checkout of the project.

**Comment by dreispt** [comment]
@sbidoul Wise words [sabom-nim](https://en.wikipedia.org/wiki/Grandmaster_(martial_arts)). I'll mumble on them...

**Comment by dreispt** [comment]
It just came to me that the `odoo start` command automatically adds the current dir to the addons path, achieving what I want. Last time I checked it was not smart enough to detect when you are in a subdir of an addons directory, but that's something that can be improved.
Thanks for your input.
